
package com.wury.soap.server.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PersonWSService", targetNamespace = "http://ws.server.soap.wury.com/", wsdlLocation = "http://localhost:8888/soap-server/persons?wsdl")
public class PersonWSService
    extends Service
{

    private final static URL PERSONWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PERSONWSSERVICE_EXCEPTION;
    private final static QName PERSONWSSERVICE_QNAME = new QName("http://ws.server.soap.wury.com/", "PersonWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/soap-server/persons?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSONWSSERVICE_WSDL_LOCATION = url;
        PERSONWSSERVICE_EXCEPTION = e;
    }

    public PersonWSService() {
        super(__getWsdlLocation(), PERSONWSSERVICE_QNAME);
    }

    public PersonWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSONWSSERVICE_QNAME, features);
    }

    public PersonWSService(URL wsdlLocation) {
        super(wsdlLocation, PERSONWSSERVICE_QNAME);
    }

    public PersonWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSONWSSERVICE_QNAME, features);
    }

    public PersonWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PersonWS
     */
    @WebEndpoint(name = "PersonWSPort")
    public PersonWS getPersonWSPort() {
        return super.getPort(new QName("http://ws.server.soap.wury.com/", "PersonWSPort"), PersonWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonWS
     */
    @WebEndpoint(name = "PersonWSPort")
    public PersonWS getPersonWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.server.soap.wury.com/", "PersonWSPort"), PersonWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSONWSSERVICE_EXCEPTION!= null) {
            throw PERSONWSSERVICE_EXCEPTION;
        }
        return PERSONWSSERVICE_WSDL_LOCATION;
    }

}
